name: spring-boot-3.2-with-Java22

env:
  JAVA_HOME: $HOME/bin/jdk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: path
        run:  echo "$JAVA_HOME/bin" >> $GITHUB_PATH

      - name: download the JDK
        run: cd $GITHUB_WORKSPACE && ./jdk.sh

      - name: "build, you beautiful thing, build!"
        run: cd $GITHUB_WORKSPACE && ./native.sh
